pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "Enhanced GNSS Location Accuracy Library"
include ':egla-location'
// include ':egla-library'  // Temporarily disabled due to KAPT JVM target issue
include ':app' 